### ISSUE TITLE
problem in file linking

### ISSUE THREAD

**Issue by viplav153** [viplav153/mess-management#5]
there is problem in media linking  can any one resolve the issue?

**Comment by chiragrathi24** [comment]
I will help you out!

**Comment by chiragrathi24** [comment]
@viplav153 assign me this task!

**Comment by Kushagra214** [comment]
I can help you out

**Comment by chiragrathi24** [comment]
@viplav153 Please mention the file for changes!

**Comment by Varun2012** [comment]
@viplav153 Assign me this task. I'll help you in this.

**Comment by Mansisrivastav** [comment]
I can help.

**Comment by Aakashsri** [comment]
i can help
