### ISSUE TITLE
plzz add readme.md file

### ISSUE THREAD

**Issue by viplav153** [viplav153/mess-management#6]
plzz add readme file with proper description

**Comment by chiragrathi24** [comment]
I will help you out!

**Comment by MisterDefender** [comment]
i will help u bro just chill

**Comment by viplav153** [comment]
@chiragrathi24  and @MisterDefender i had assigned you please solve this issue

**Comment by cgoxo** [comment]
Assgin me in..

**Comment by Kushagra214** [comment]
I can help you!

**Comment by aakashsri101** [comment]
I can help

**Comment by Varun2012** [comment]
@viplav153 Assign me. I can help you.

**Comment by HarshBhadouria** [comment]
i want to suggest changes.

**Comment by Aakashsri** [comment]
Hey Viplav, Let me help you
